### ISSUE TITLE
Request icons

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/social.svg.min#2]
Please always link to the official brand page and vector assets when requesting (if available).
## Example request

Twitter https://about.twitter.com/company/brand-assets
Twitter https://g.twimg.com/brand_guideline_logos_0.zip

**Comment by Gunny123** [comment]
<b>Soundcloud</b>
https://soundcloud.com/press
https://soundcloud.com/pages/embed
https://developers.soundcloud.com/docs/api/buttons-logos

I didn't find exactly what you may be looking for as I am no expert.

**Comment by larsenwork** [comment]
@Gunny123 it's still fairly big but also a complex logo :) https://github.com/larsenwork/social.svg.min/blob/master/icons/SoundCloud%20%23ff8800%20%23ff3300.svg

**Comment by larsenwork** [comment]
@Gunny123 added a version without text too - it's smaller

**Comment by Gunny123** [comment]
@larsenwork Awesome.

**Comment by badcat** [comment]
Love this!

Maybe the Houzz logo would be a good one?

House (Official) http://www.houzz.com/download/resources/houzz_logo.zip  (only PNG and EPS)
Unofficial Stacked with Type  http://seeklogo.com/houzz-logo-220063.html

**Comment by wtfaremyinitials** [comment]
**Snapchat**
https://support-tools.storage.googleapis.com/Logo_downloads-77861962.zip

Love the project by the way! Thanks

**Comment by Gunny123** [comment]
<b>Reddit</b>
https://www.reddit.com/about/alien/

I guess this is an obvious one lol

**Comment by larsenwork** [comment]
@badcat not sure if Houzz is a social platform similar to the others? Don't want to bloat with edge-case icons.
@wtfaremyinitials and @Gunny123 
![screen shot 2016-01-01 at 15 57 22](https://cloud.githubusercontent.com/assets/3859425/12071219/60ec0d18-b0a0-11e5-9817-b574d71a493c.png)

Edit: had to add some styling, not sure if this is the best way to do it: https://github.com/larsenwork/social.svg.min/blob/3376e95bdaee13db323cc47f987b9b7c0dde4af4/codepen/codepen.scss#L85-L114

**Comment by Gunny123** [comment]
@larsenwork I tried to find Snoo with just his head, but I couldn't find official images per say. Also, when no background is toggled the yellow shouldn't fill the ghost. I believe its just white with a <a href="https://www.snapchat.com/brand-guidelines" target="_blank">black border outline as per their brand assets page.</a>

**Comment by badcat** [comment]
@larsenwork  OK. No problem.  I don't understand the bloat part though.  They're just icons that can be used independently of the others, right?

Any who - Houzz has 10 times more employees than Reddit and over 35 Million unique visitors a month.  Go figure :)  - https://en.wikipedia.org/wiki/Houzz

**Comment by larsenwork** [comment]
@badcat forgive my ignorance but I've just never seen a houzz logo anywhere but on houzz.com - even home decor sites like apartment therapy doesn't use it?

**Comment by larsenwork** [comment]
@Gunny123 added a head only version and fixed snapchat (should be black as per brand assets) 
![screen shot 2016-01-01 at 19 28 34](https://cloud.githubusercontent.com/assets/3859425/12071776/e530aca6-b0bd-11e5-93ae-d74356e08d59.png)

**Comment by huphtur** [comment]
Rdio! :(

Feed Icon (RSS) please: http://www.feedicons.com/

**Comment by larsenwork** [comment]
@huphtur why the sad face?

**Comment by badcat** [comment]
@larsenwork Probably because there's no more Rdio?
http://www.rdio.com/farewell/

**Comment by larsenwork** [comment]
@badcat cheers
@huphtur rss added

**Comment by huphtur** [comment]
Couple more (planning to incorporate in personal blog soon):
- [Gmail](http://setup.googleapps.com/setup/resources/logos/)
- Flickr (couldn't find official brand guidelines but logo shouldn't be too hard to reproduce right? 😜)
- Delicious (same as Flickr)

**Comment by Gunny123** [comment]
@huphtur @larsenwork <a href="http://imgur.com/65ibZvY" target="_blank">I found this for flickr</a>

**Comment by larsenwork** [comment]
@huphtur not sure if Gmail is easily convertible 
@Gunny123 cheers, I always use this: https://bendodson.com/projects/itunes-artwork-finder/index.html if there aren't any downloadable official icons

**Comment by huphtur** [comment]
http://svgporn.com/ Could help too perhaps?

**Comment by larsenwork** [comment]
@huphtur svgporn gmail colors + shading is off compared to the iOS app icon and the overall icon is fairly far from the rest of the single color social icons so not sure if it fits this project (badges were already a stretch but I needed those for work...) 
![1024x1024bb](https://cloud.githubusercontent.com/assets/3859425/12245936/e0a8c75e-b8ab-11e5-8a62-2266a73f1653.jpg)

**Comment by larsenwork** [comment]
added flickr
added delicious (svg only - didn't really fit the sass function + other icons)

**Comment by larsenwork** [comment]
What would make more sense would probably be to add some generic contact/email icons that could be monochrome and fit most of the other social icons

**Comment by huphtur** [comment]
:+1:

**Comment by larsenwork** [comment]
![screen shot 2016-01-13 at 00 31 38](https://cloud.githubusercontent.com/assets/3859425/12280294/1e65c330-b98d-11e5-830c-f73fdece577d.png)

**Comment by larsenwork** [comment]
![screen shot 2016-01-19 at 22 06 23](https://cloud.githubusercontent.com/assets/3859425/12432530/1ddbe0f6-befc-11e5-9b3d-4e5513a2fc15.png)
Could maybe add a gmail like this

**Comment by Gunny123** [comment]
**Amazon**

Would it be possible to replicate [font-awesome's](http://fortawesome.github.io/Font-Awesome/icon/amazon/) rendition of Amazon?

Amazon seemingly only publishes its [full badges here](https://images-na.ssl-images-amazon.com/images/G/01/AdvertisingSite/pdfs/AmazonBrandUsageGuidelines.pdf).

**Comment by kartikanand** [comment]
**StackOverflow**

Link to official SVG icons - http://stackapps.com/questions/347/svg-versions-of-the-logos

**Comment by larsenwork** [comment]
@Gunny123 coming soon (been busy:) 
@kartikanand please take screenshot of the exact version you're thinking of.

**Comment by kartikanand** [comment]
@larsenwork I was thinking of this one: 

![so](https://cloud.githubusercontent.com/assets/1916792/14101018/2f47e512-f5af-11e5-9262-efb481e1cda1.png)

I tried minimizing it through SVGO here : https://jakearchibald.github.io/svgomg/, but being a SVG noob the resulting icon wasn't scaling perfectly as yours do :D

**Comment by Gunny123** [comment]
Can we get an update to the Instagram icon?

**Comment by larsenwork** [comment]
@Gunny123 instagram should be there
added amazon too

**Comment by Gunny123** [comment]
[The new Instagram icon.](https://www.instagram-brand.com/) @larsenwork

**Comment by larsenwork** [comment]
https://github.com/larsenwork/web.svg.min/blob/d3d7db6eb7cd1721a72ebb1810b15889257701e3/svg/social%20icons:logos/instagram.svg

**Comment by Gunny123** [comment]
I just didn't see it on Codepen or the markdown file

**Comment by Knogobert** [comment]
Could you add our fellow neighbour Norway's flag to your nice collection?

**Comment by larsenwork** [comment]
@Knogobert sure, should add all the scandinavian once while I'm at it. I'm closing this issue so everyone please create separate issues for each request. It makes it easier for me to track :)
