### ISSUE TITLE
[Request] YouTube

### ISSUE THREAD

**Issue by arocks** [larsenwork/social.svg.min#3]
Thank you so much for these icons... Would be great if you could add a YouTube icon

YouTube https://www.youtube.com/yt/brand/
YouTube https://www.youtube.com/yt/brand/using-logo.html

**Comment by larsenwork** [comment]
👍 you were one minute early: https://github.com/larsenwork/social.svg.min/commit/ccc78512255b31ecd3527aec48707a776eedea26

**Comment by arocks** [comment]
Thanks! :+1:
