### ISSUE TITLE
Instagram launched a new logo...

### ISSUE THREAD

**Issue by Gunny123** [larsenwork/social.svg.min#4]
https://www.instagram.com/press/?hl=en

**Comment by wongjn** [comment]
This is something I have thrown up quickly for my own personal use. Feel free to use it or edit it to your own needs until the proper SVG comes along. This hasn't been run through SVGO so you may want to do that.

``` SVG
<svg xmlns="http://www.w3.org/2000/svg" width="1010" height="1010" viewBox="0 0 1010 1010">
  <circle cx="774" cy="236" r="61"/>
  <circle cx="505" cy="505" r="213" fill="none" stroke="#000" stroke-width="92"/>
  <path d="M963,691c0,185-85,263-270,270-103,4-269,4-372,0C136,954,58,876,51,691c-4-95-4-186,0-372S136,56,321,49c103-4,269-4,372,0,185,7,263,85,270,270V691Z" fill="none" stroke="#000" stroke-width="91"/>
</svg>
```

**Comment by larsenwork** [comment]
@SaltPacket cheers, I prefer to having points at the extrema (to avoid browser clipping) and stick to fill (for styling consistency purposes) so I've made I slightly different version which is a bit bigger in file size though 😄
